import React, { createContext, useContext, useState, useEffect, useCallback, ReactNode } from 'react';
import { SUPPORTED_LANGUAGES } from '../services/translationService';
import { getApiBaseUrl } from '../services/apiService';

// Pre-translated UI strings for all supported languages
// This ensures instant language switching without API calls
const UI_TRANSLATIONS: Record<string, Record<string, string>> = {
    en: {
        // Navigation
        home: 'Home',
        explore: 'Explore',
        read: 'Read',
        listen: 'Listen',
        settings: 'Settings',
        profile: 'Profile',
        library: 'Library',
        
        // Actions
        play: 'Play',
        pause: 'Pause',
        stop: 'Stop',
        continue: 'Continue',
        next: 'Next',
        back: 'Back',
        skip: 'Skip',
        retry: 'Retry',
        save: 'Save',
        cancel: 'Cancel',
        close: 'Close',
        done: 'Done',
        signIn: 'Sign In',
        signOut: 'Sign Out',
        logOut: 'LOG OUT',
        
        // Sections
        dailyLessons: 'Daily Lessons',
        featuredBooks: 'Featured Books',
        recentlyRead: 'Recently Read',
        favorites: 'Favorites',
        categories: 'Categories',
        allBooks: 'All Books',
        audioBooks: 'Audio Books',
        
        // Book Reader
        readAloud: 'Read Aloud',
        autoPlay: 'Auto Play',
        voice: 'Voice',
        language: 'Language',
        selectLanguage: 'Select Language',
        
        // Lessons
        watchVideo: 'Watch Video',
        devotional: 'Devotional',
        activity: 'Activity',
        quiz: 'Quiz',
        takeQuiz: 'Take Quiz',
        episode: 'Episode',
        
        // Settings
        account: 'Account',
        notifications: 'Notifications',
        appearance: 'Appearance',
        privacy: 'Privacy',
        help: 'Help',
        about: 'About',
        audioNotifications: 'Audio & Notifications',
        backgroundMusic: 'Background Music',
        soundEffects: 'Sound Effects',
        appLanguage: 'App Language',
        
        // Common
        loading: 'Loading...',
        error: 'Error',
        success: 'Success',
        noResults: 'No results found',
        searchPlaceholder: 'Search...',
        
        // Messages
        welcome: 'Welcome',
        greatJob: 'Great job!',
        keepGoing: 'Keep going!',
        theEnd: 'The End!',
        whatNext: "Great reading! What's next?",
        readAgain: 'Read Again',
        addToFavorites: 'Add to Favorites',
        removeFromFavorites: 'Remove from Favorites',
        adventureAwaits: 'Adventure Awaits!',
        termsConditions: 'By continuing you agree to our Terms & Conditions',
        appDisplayLanguage: 'The app will be displayed in your selected language',
        changesLanguageInterface: 'Changes the language of the app interface and automatically translates book text.',
        // Profile Page
        profiles: 'Profiles',
        chooseExplorer: 'Choose Explorer',
        whosPlayingToday: "Who's playing today?",
        addProfile: 'Add Profile',
        parent: 'Parent',
        // Home Page
        hiExplorer: 'Hi Explorer!',
        letsDiveIn: "Let's Dive in.",
        thisWeeksProgress: "This Week's Progress",
        days: 'Days',
        dailyTasksIQGames: 'Daily Tasks & IQ Games',
        restPlayDay: 'Rest & Play Day!',
        noLessonsToday: 'No lessons today. Enjoy reading stories or playing games with family!',
        tapAnotherDay: 'Tap another day above to view those lessons.',
        // Book details
        byAuthor: 'by',
        readNow: 'Read Now',
        listenNow: 'Listen Now',
        pages: 'pages',
        minutes: 'minutes',
        // Categories
        allCategories: 'All Categories',
        bibleStories: 'Bible Stories',
        faithValues: 'Faith & Values',
        prayerDevotional: 'Prayer & Devotional',
        // Common actions
        seeAll: 'See All',
        viewAll: 'View All',
        search: 'Search',
        filter: 'Filter',
        sort: 'Sort',
        
        // Onboarding
        welcomeToGodlyKids: 'Welcome to Godly Kids!',
        discoverAmazingStories: 'Discover amazing Bible stories',
        learnAndGrow: 'Learn and Grow',
        buildYourFaith: 'Build your faith with fun activities',
        readAndListen: 'Read & Listen',
        enjoyInteractiveBooks: 'Enjoy interactive books with audio',
        trackProgress: 'Track Progress',
        seeYourGrowth: 'See your growth and achievements',
        getStarted: 'Get Started',
        letsGo: "Let's Go!",
        storiesAdventures: 'Stories & Adventures',
        exploreStories: 'Explore Bible stories with beautiful illustrations and read-along audio!',
        funGamesTitle: 'Fun Games & Challenges',
        playMemoryGames: 'Play memory games, daily challenges, and earn gold coins!',
        watchVideoLessons: 'Watch video lessons, complete activities, and grow in faith every day!',
        
        // Profile/Avatar Page
        yourAvatar: 'Your Avatar',
        readyForAdventures: 'Ready for Adventures!',
        goPremium: 'Go Premium',
        editProfile: 'Edit Profile',
        visitShop: 'Visit Shop',
        unlockAllStoriesItems: 'Unlock all stories & items',
        builderShop: 'Builder Shop',
        customizeYourAvatar: 'Customize Your Avatar',
        heads: 'Heads',
        bodies: 'Bodies',
        hats: 'Hats',
        accessories: 'Accessories',
        backgrounds: 'Backgrounds',
        equipped: 'Equipped',
        equip: 'Equip',
        buy: 'Buy',
        coins: 'Coins',
        owned: 'Owned',
        locked: 'Locked',
        
        // Settings extras
        support: 'Support',
        privacyPolicy: 'Privacy Policy',
        termsAndConditions: 'Terms & Conditions',
        helpCenter: 'Help Center',
        restorePurchases: 'Restore Purchases',
        contactUs: 'Contact Us',
        version: 'Version',
        
        // Navigation wheel
        books: 'Books',
        audio: 'Audio',
        lessons: 'Lessons',
        games: 'Games',
        
        // Report Card
        reportCard: 'Report Card',
        yourProgress: 'Your Progress',
        booksRead: 'Books Read',
        lessonsCompleted: 'Lessons Completed',
        daysStreak: 'Days Streak',
        totalPoints: 'Total Points',
        achievements: 'Achievements',
        keepItUp: 'Keep it up!',
        
        // Games
        dailyChallenge: 'Daily Challenge',
        memoryGame: 'Memory Game',
        prayerTime: 'Prayer Time',
        strengthBuilder: 'Strength Builder',
        playNow: 'Play Now',
        highScore: 'High Score',
        divinePairs: 'Divine Pairs',
        comeBackSoon: 'Come Back Soon!',
        memoryChallengeCompleted: "You've already completed today's memory challenge. The next challenge will be available in:",
        resetsEvery12Hours: '(Resets every 12 hours)',
        memoryChallenge: 'Memory Challenge',
        flipCardsToMatch: 'Flip the cards to match the divine symbols!',
        findThemQuickly: 'Find them all quickly for 3 stars.',
        startGame: 'START',
        pairs: 'Pairs',
        timesUp: "Time's Up!",
        keepPracticing: 'Keep practicing your memory!',
        tryAgain: 'TRY AGAIN',
        sharpMind: 'SHARP MIND!',
        foundAllPairs: 'You found all the divine pairs!',
        claimCoins: 'CLAIM',
        
        // Strength Builder Game
        strengthBuilderGame: 'Strength Builder',
        spiritualStrength: 'Spiritual Strength',
        verseChallenge: 'Verse Challenge',
        reciteVerse: 'Recite the verse correctly!',
        tapWordsInOrder: 'Tap the words in order',
        verseCompleted: 'Verse Completed!',
        excellent: 'Excellent!',
        
        // Prayer Time Game
        prayerTimeGame: 'Prayer Time',
        dailyPrayer: 'Daily Prayer',
        writeYourPrayer: 'Write your prayer...',
        submitPrayer: 'Submit Prayer',
        prayerSubmitted: 'Prayer Submitted!',
        thankYouForPraying: 'Thank you for praying!',
        
        // Report Card
        overview: 'Overview',
        activityHistory: 'Activity',
        thisWeek: 'This Week',
        thisMonth: 'This Month',
        pagesReadStat: 'Pages Read',
        songsListened: 'Songs Listened',
        gamesPlayed: 'Games Played',
        coinsEarned: 'Coins Earned',
        timeSpent: 'Time Spent',
        recentActivity: 'Recent Activity',
        noRecentActivity: 'No recent activity found',
        justNow: 'Just now',
        minsAgo: 'm ago',
        hoursAgo: 'h ago',
        daysAgo: 'd ago',
        
        // Playlist/Book details
        playlist: 'Playlist',
        tracks: 'tracks',
        duration: 'Duration',
        playAll: 'Play All',
        shuffle: 'Shuffle',
        description: 'Description',
        moreInfo: 'More Info',
        ageGroup: 'Age Group',
        level: 'Level',
        
        // Common extra
        premium: 'Premium',
        free: 'Free',
        new: 'New',
        popular: 'Popular',
        recommended: 'Recommended',
        complete: 'Complete',
        incomplete: 'Incomplete',
        start: 'Start',
        resume: 'Resume',
        
        // Book/Playlist details
        saveToLibrary: 'Save to Library',
        savedToLibrary: 'Saved to Library',
        myReads: 'My Reads',
        myListens: 'My Listens',
        completeBookToUnlock: 'Complete book to unlock',
        spinWheelToNavigate: 'Spin the wheel to navigate!',
    },
    es: {
        // Navigation
        home: 'Inicio',
        explore: 'Explorar',
        read: 'Leer',
        listen: 'Escuchar',
        settings: 'Ajustes',
        profile: 'Perfil',
        library: 'Biblioteca',
        
        // Actions
        play: 'Reproducir',
        pause: 'Pausar',
        stop: 'Detener',
        continue: 'Continuar',
        next: 'Siguiente',
        back: 'Atrás',
        skip: 'Omitir',
        retry: 'Reintentar',
        save: 'Guardar',
        cancel: 'Cancelar',
        close: 'Cerrar',
        done: 'Listo',
        signIn: 'Iniciar sesión',
        signOut: 'Cerrar sesión',
        logOut: 'CERRAR SESIÓN',
        
        // Sections
        dailyLessons: 'Lecciones Diarias',
        featuredBooks: 'Libros Destacados',
        recentlyRead: 'Leídos Recientemente',
        favorites: 'Favoritos',
        categories: 'Categorías',
        allBooks: 'Todos los Libros',
        audioBooks: 'Audiolibros',
        
        // Book Reader
        readAloud: 'Leer en Voz Alta',
        autoPlay: 'Reproducción Automática',
        voice: 'Voz',
        language: 'Idioma',
        selectLanguage: 'Seleccionar Idioma',
        
        // Lessons
        watchVideo: 'Ver Video',
        devotional: 'Devocional',
        activity: 'Actividad',
        quiz: 'Cuestionario',
        takeQuiz: 'Hacer Cuestionario',
        episode: 'Episodio',
        
        // Settings
        account: 'Cuenta',
        notifications: 'Notificaciones',
        appearance: 'Apariencia',
        privacy: 'Privacidad',
        help: 'Ayuda',
        about: 'Acerca de',
        audioNotifications: 'Audio y Notificaciones',
        backgroundMusic: 'Música de Fondo',
        soundEffects: 'Efectos de Sonido',
        appLanguage: 'Idioma de la App',
        
        // Common
        loading: 'Cargando...',
        error: 'Error',
        success: 'Éxito',
        noResults: 'No se encontraron resultados',
        searchPlaceholder: 'Buscar...',
        
        // Messages
        welcome: 'Bienvenido',
        greatJob: '¡Buen trabajo!',
        keepGoing: '¡Sigue así!',
        theEnd: '¡El Fin!',
        whatNext: '¡Excelente lectura! ¿Qué sigue?',
        readAgain: 'Leer de Nuevo',
        addToFavorites: 'Añadir a Favoritos',
        removeFromFavorites: 'Quitar de Favoritos',
        adventureAwaits: '¡La Aventura Te Espera!',
        termsConditions: 'Al continuar aceptas nuestros Términos y Condiciones',
        appDisplayLanguage: 'La aplicación se mostrará en el idioma seleccionado',
        changesLanguageInterface: 'Cambia el idioma de la interfaz de la aplicación y traduce automáticamente el texto de los libros.',
        // Profile Page
        profiles: 'Perfiles',
        chooseExplorer: 'Elige Explorador',
        whosPlayingToday: '¿Quién juega hoy?',
        addProfile: 'Añadir Perfil',
        parent: 'Padre',
        // Home Page
        hiExplorer: '¡Hola Explorador!',
        letsDiveIn: 'Vamos a sumergirnos.',
        thisWeeksProgress: 'Progreso de Esta Semana',
        days: 'Días',
        dailyTasksIQGames: 'Tareas Diarias y Juegos de IQ',
        restPlayDay: '¡Día de Descanso y Juego!',
        noLessonsToday: 'No hay lecciones hoy. ¡Disfruta leyendo historias o jugando con la familia!',
        tapAnotherDay: 'Toca otro día arriba para ver esas lecciones.',
        // Book details
        byAuthor: 'por',
        readNow: 'Leer Ahora',
        listenNow: 'Escuchar Ahora',
        pages: 'páginas',
        minutes: 'minutos',
        // Categories
        allCategories: 'Todas las Categorías',
        bibleStories: 'Historias Bíblicas',
        faithValues: 'Fe y Valores',
        prayerDevotional: 'Oración y Devocional',
        // Common actions
        seeAll: 'Ver Todo',
        viewAll: 'Ver Todo',
        search: 'Buscar',
        filter: 'Filtrar',
        sort: 'Ordenar',
        
        // Onboarding
        welcomeToGodlyKids: '¡Bienvenido a Godly Kids!',
        discoverAmazingStories: 'Descubre increíbles historias bíblicas',
        learnAndGrow: 'Aprende y Crece',
        buildYourFaith: 'Construye tu fe con actividades divertidas',
        readAndListen: 'Lee y Escucha',
        enjoyInteractiveBooks: 'Disfruta de libros interactivos con audio',
        trackProgress: 'Sigue tu Progreso',
        seeYourGrowth: 'Ve tu crecimiento y logros',
        getStarted: 'Comenzar',
        letsGo: '¡Vamos!',
        storiesAdventures: 'Historias y Aventuras',
        exploreStories: '¡Explora historias bíblicas con hermosas ilustraciones y audio para leer!',
        funGamesTitle: 'Juegos y Desafíos Divertidos',
        playMemoryGames: '¡Juega juegos de memoria, desafíos diarios y gana monedas de oro!',
        watchVideoLessons: '¡Mira lecciones en video, completa actividades y crece en la fe cada día!',
        
        // Profile/Avatar Page
        yourAvatar: 'Tu Avatar',
        readyForAdventures: '¡Listo para Aventuras!',
        goPremium: 'Hazte Premium',
        editProfile: 'Editar Perfil',
        visitShop: 'Visitar Tienda',
        unlockAllStoriesItems: 'Desbloquea todas las historias y artículos',
        builderShop: 'Tienda del Constructor',
        customizeYourAvatar: 'Personaliza tu Avatar',
        heads: 'Cabezas',
        bodies: 'Cuerpos',
        hats: 'Sombreros',
        accessories: 'Accesorios',
        backgrounds: 'Fondos',
        equipped: 'Equipado',
        equip: 'Equipar',
        buy: 'Comprar',
        coins: 'Monedas',
        owned: 'Adquirido',
        locked: 'Bloqueado',
        
        // Settings extras
        support: 'Soporte',
        privacyPolicy: 'Política de Privacidad',
        termsAndConditions: 'Términos y Condiciones',
        helpCenter: 'Centro de Ayuda',
        restorePurchases: 'Restaurar Compras',
        contactUs: 'Contáctanos',
        version: 'Versión',
        
        // Navigation wheel
        books: 'Libros',
        audio: 'Audio',
        lessons: 'Lecciones',
        games: 'Juegos',
        
        // Report Card
        reportCard: 'Boleta de Calificaciones',
        yourProgress: 'Tu Progreso',
        booksRead: 'Libros Leídos',
        lessonsCompleted: 'Lecciones Completadas',
        daysStreak: 'Días Seguidos',
        totalPoints: 'Puntos Totales',
        achievements: 'Logros',
        keepItUp: '¡Sigue así!',
        
        // Games
        dailyChallenge: 'Desafío Diario',
        memoryGame: 'Juego de Memoria',
        prayerTime: 'Hora de Oración',
        strengthBuilder: 'Constructor de Fortaleza',
        playNow: 'Jugar Ahora',
        highScore: 'Puntuación Más Alta',
        divinePairs: 'Parejas Divinas',
        comeBackSoon: '¡Vuelve Pronto!',
        memoryChallengeCompleted: 'Ya completaste el desafío de memoria de hoy. El próximo desafío estará disponible en:',
        resetsEvery12Hours: '(Se reinicia cada 12 horas)',
        memoryChallenge: 'Desafío de Memoria',
        flipCardsToMatch: '¡Voltea las cartas para emparejar los símbolos divinos!',
        findThemQuickly: 'Encuéntralos rápido para 3 estrellas.',
        startGame: 'INICIAR',
        pairs: 'Parejas',
        timesUp: '¡Se Acabó el Tiempo!',
        keepPracticing: '¡Sigue practicando tu memoria!',
        tryAgain: 'INTENTAR DE NUEVO',
        sharpMind: '¡MENTE AGUDA!',
        foundAllPairs: '¡Encontraste todas las parejas divinas!',
        claimCoins: 'RECLAMAR',
        
        // Strength Builder Game
        strengthBuilderGame: 'Constructor de Fortaleza',
        spiritualStrength: 'Fortaleza Espiritual',
        verseChallenge: 'Desafío de Versículos',
        reciteVerse: '¡Recita el versículo correctamente!',
        tapWordsInOrder: 'Toca las palabras en orden',
        verseCompleted: '¡Versículo Completado!',
        excellent: '¡Excelente!',
        
        // Prayer Time Game
        prayerTimeGame: 'Hora de Oración',
        dailyPrayer: 'Oración Diaria',
        writeYourPrayer: 'Escribe tu oración...',
        submitPrayer: 'Enviar Oración',
        prayerSubmitted: '¡Oración Enviada!',
        thankYouForPraying: '¡Gracias por orar!',
        
        // Report Card extra
        overview: 'Resumen',
        activityHistory: 'Actividad',
        thisWeek: 'Esta Semana',
        thisMonth: 'Este Mes',
        pagesReadStat: 'Páginas Leídas',
        songsListened: 'Canciones Escuchadas',
        gamesPlayed: 'Juegos Jugados',
        coinsEarned: 'Monedas Ganadas',
        timeSpent: 'Tiempo Dedicado',
        recentActivity: 'Actividad Reciente',
        noRecentActivity: 'No se encontró actividad reciente',
        justNow: 'Ahora mismo',
        minsAgo: 'm atrás',
        hoursAgo: 'h atrás',
        daysAgo: 'd atrás',
        
        // Playlist/Book details
        playlist: 'Lista de Reproducción',
        tracks: 'pistas',
        duration: 'Duración',
        playAll: 'Reproducir Todo',
        shuffle: 'Aleatorio',
        description: 'Descripción',
        moreInfo: 'Más Información',
        ageGroup: 'Grupo de Edad',
        level: 'Nivel',
        
        // Common extra
        premium: 'Premium',
        free: 'Gratis',
        new: 'Nuevo',
        popular: 'Popular',
        recommended: 'Recomendado',
        complete: 'Completo',
        incomplete: 'Incompleto',
        start: 'Iniciar',
        resume: 'Continuar',
        
        // Book/Playlist details
        saveToLibrary: 'Guardar en Biblioteca',
        savedToLibrary: 'Guardado en Biblioteca',
        myReads: 'Mis Lecturas',
        myListens: 'Mis Escuchas',
        completeBookToUnlock: 'Completa el libro para desbloquear',
        spinWheelToNavigate: '¡Gira la rueda para navegar!',
    },
    pt: {
        home: 'Início',
        explore: 'Explorar',
        read: 'Ler',
        listen: 'Ouvir',
        settings: 'Configurações',
        profile: 'Perfil',
        library: 'Biblioteca',
        play: 'Reproduzir',
        pause: 'Pausar',
        stop: 'Parar',
        continue: 'Continuar',
        next: 'Próximo',
        back: 'Voltar',
        skip: 'Pular',
        retry: 'Tentar novamente',
        save: 'Salvar',
        cancel: 'Cancelar',
        close: 'Fechar',
        done: 'Concluído',
        signIn: 'Entrar',
        signOut: 'Sair',
        logOut: 'SAIR',
        dailyLessons: 'Lições Diárias',
        featuredBooks: 'Livros em Destaque',
        recentlyRead: 'Lidos Recentemente',
        favorites: 'Favoritos',
        categories: 'Categorias',
        allBooks: 'Todos os Livros',
        audioBooks: 'Audiolivros',
        readAloud: 'Ler em Voz Alta',
        autoPlay: 'Reprodução Automática',
        voice: 'Voz',
        language: 'Idioma',
        selectLanguage: 'Selecionar Idioma',
        watchVideo: 'Assistir Vídeo',
        devotional: 'Devocional',
        activity: 'Atividade',
        quiz: 'Quiz',
        takeQuiz: 'Fazer Quiz',
        episode: 'Episódio',
        account: 'Conta',
        notifications: 'Notificações',
        appearance: 'Aparência',
        privacy: 'Privacidade',
        help: 'Ajuda',
        about: 'Sobre',
        audioNotifications: 'Áudio e Notificações',
        backgroundMusic: 'Música de Fundo',
        soundEffects: 'Efeitos Sonoros',
        appLanguage: 'Idioma do App',
        loading: 'Carregando...',
        error: 'Erro',
        success: 'Sucesso',
        noResults: 'Nenhum resultado encontrado',
        searchPlaceholder: 'Pesquisar...',
        welcome: 'Bem-vindo',
        greatJob: 'Ótimo trabalho!',
        keepGoing: 'Continue assim!',
        theEnd: 'Fim!',
        whatNext: 'Ótima leitura! O que vem a seguir?',
        readAgain: 'Ler Novamente',
        addToFavorites: 'Adicionar aos Favoritos',
        removeFromFavorites: 'Remover dos Favoritos',
        adventureAwaits: 'A Aventura Espera!',
        termsConditions: 'Ao continuar, você concorda com nossos Termos e Condições',
        appDisplayLanguage: 'O aplicativo será exibido no idioma selecionado',
        changesLanguageInterface: 'Altera o idioma da interface do aplicativo e traduz automaticamente o texto dos livros.',
        
        // Onboarding
        welcomeToGodlyKids: 'Bem-vindo ao Godly Kids!',
        discoverAmazingStories: 'Descubra histórias bíblicas incríveis',
        learnAndGrow: 'Aprenda e Cresça',
        buildYourFaith: 'Construa sua fé com atividades divertidas',
        readAndListen: 'Leia e Ouça',
        enjoyInteractiveBooks: 'Aproveite livros interativos com áudio',
        trackProgress: 'Acompanhe o Progresso',
        seeYourGrowth: 'Veja seu crescimento e conquistas',
        getStarted: 'Começar',
        letsGo: 'Vamos!',
        yourAvatar: 'Seu Avatar',
        readyForAdventures: 'Pronto para Aventuras!',
        goPremium: 'Seja Premium',
        editProfile: 'Editar Perfil',
        visitShop: 'Visitar Loja',
        builderShop: 'Loja do Construtor',
        customizeYourAvatar: 'Personalize seu Avatar',
        heads: 'Cabeças',
        bodies: 'Corpos',
        hats: 'Chapéus',
        accessories: 'Acessórios',
        backgrounds: 'Fundos',
        equipped: 'Equipado',
        equip: 'Equipar',
        buy: 'Comprar',
        coins: 'Moedas',
        owned: 'Adquirido',
        locked: 'Bloqueado',
        support: 'Suporte',
        privacyPolicy: 'Política de Privacidade',
        termsAndConditions: 'Termos e Condições',
        helpCenter: 'Central de Ajuda',
        restorePurchases: 'Restaurar Compras',
        contactUs: 'Fale Conosco',
        version: 'Versão',
        books: 'Livros',
        audio: 'Áudio',
        lessons: 'Lições',
        games: 'Jogos',
        reportCard: 'Boletim',
        yourProgress: 'Seu Progresso',
        booksRead: 'Livros Lidos',
        lessonsCompleted: 'Lições Completadas',
        daysStreak: 'Dias Seguidos',
        totalPoints: 'Pontos Totais',
        achievements: 'Conquistas',
        keepItUp: 'Continue assim!',
        dailyChallenge: 'Desafio Diário',
        memoryGame: 'Jogo da Memória',
        prayerTime: 'Hora da Oração',
        strengthBuilder: 'Construtor de Força',
        playNow: 'Jogar Agora',
        highScore: 'Maior Pontuação',
        divinePairs: 'Pares Divinos',
        comeBackSoon: 'Volte Logo!',
        memoryChallengeCompleted: 'Você já completou o desafio de memória de hoje. O próximo desafio estará disponível em:',
        resetsEvery12Hours: '(Reinicia a cada 12 horas)',
        memoryChallenge: 'Desafio de Memória',
        flipCardsToMatch: 'Vire as cartas para combinar os símbolos divinos!',
        findThemQuickly: 'Encontre todos rapidamente para 3 estrelas.',
        startGame: 'INICIAR',
        pairs: 'Pares',
        timesUp: 'Tempo Esgotado!',
        keepPracticing: 'Continue praticando sua memória!',
        tryAgain: 'TENTAR NOVAMENTE',
        sharpMind: 'MENTE AFIADA!',
        foundAllPairs: 'Você encontrou todos os pares divinos!',
        claimCoins: 'RESGATAR',
        strengthBuilderGame: 'Construtor de Força',
        spiritualStrength: 'Força Espiritual',
        verseChallenge: 'Desafio de Versículos',
        reciteVerse: 'Recite o versículo corretamente!',
        tapWordsInOrder: 'Toque nas palavras em ordem',
        verseCompleted: 'Versículo Completado!',
        excellent: 'Excelente!',
        prayerTimeGame: 'Hora da Oração',
        dailyPrayer: 'Oração Diária',
        writeYourPrayer: 'Escreva sua oração...',
        submitPrayer: 'Enviar Oração',
        prayerSubmitted: 'Oração Enviada!',
        thankYouForPraying: 'Obrigado por orar!',
        overview: 'Visão Geral',
        activityHistory: 'Atividade',
        thisWeek: 'Esta Semana',
        thisMonth: 'Este Mês',
        pagesReadStat: 'Páginas Lidas',
        songsListened: 'Músicas Ouvidas',
        gamesPlayed: 'Jogos Jogados',
        coinsEarned: 'Moedas Ganhas',
        timeSpent: 'Tempo Gasto',
        recentActivity: 'Atividade Recente',
        noRecentActivity: 'Nenhuma atividade recente encontrada',
        justNow: 'Agora mesmo',
        minsAgo: 'm atrás',
        hoursAgo: 'h atrás',
        daysAgo: 'd atrás',
        playlist: 'Playlist',
        tracks: 'faixas',
        duration: 'Duração',
        playAll: 'Reproduzir Tudo',
        shuffle: 'Aleatório',
        description: 'Descrição',
        moreInfo: 'Mais Informações',
        ageGroup: 'Faixa Etária',
        level: 'Nível',
        premium: 'Premium',
        free: 'Grátis',
        new: 'Novo',
        popular: 'Popular',
        recommended: 'Recomendado',
        complete: 'Completo',
        incomplete: 'Incompleto',
        start: 'Iniciar',
        resume: 'Continuar',
        profiles: 'Perfis',
        chooseExplorer: 'Escolha Explorador',
        whosPlayingToday: 'Quem joga hoje?',
        addProfile: 'Adicionar Perfil',
        parent: 'Pai/Mãe',
        hiExplorer: 'Olá Explorador!',
        letsDiveIn: 'Vamos mergulhar.',
        thisWeeksProgress: 'Progresso desta Semana',
        days: 'Dias',
        dailyTasksIQGames: 'Tarefas Diárias e Jogos de QI',
        restPlayDay: 'Dia de Descanso e Diversão!',
        noLessonsToday: 'Sem lições hoje. Aproveite lendo histórias ou jogando com a família!',
        tapAnotherDay: 'Toque em outro dia acima para ver essas lições.',
        byAuthor: 'por',
        readNow: 'Ler Agora',
        listenNow: 'Ouvir Agora',
        pages: 'páginas',
        minutes: 'minutos',
        allCategories: 'Todas as Categorias',
        bibleStories: 'Histórias Bíblicas',
        faithValues: 'Fé e Valores',
        prayerDevotional: 'Oração e Devocional',
        seeAll: 'Ver Tudo',
        viewAll: 'Ver Tudo',
        search: 'Pesquisar',
        filter: 'Filtrar',
        sort: 'Ordenar',
    },
    fr: {
        home: 'Accueil',
        explore: 'Explorer',
        read: 'Lire',
        listen: 'Écouter',
        settings: 'Paramètres',
        profile: 'Profil',
        library: 'Bibliothèque',
        play: 'Lecture',
        pause: 'Pause',
        stop: 'Arrêter',
        continue: 'Continuer',
        next: 'Suivant',
        back: 'Retour',
        skip: 'Passer',
        retry: 'Réessayer',
        save: 'Enregistrer',
        cancel: 'Annuler',
        close: 'Fermer',
        done: 'Terminé',
        signIn: 'Se connecter',
        signOut: 'Se déconnecter',
        logOut: 'DÉCONNEXION',
        dailyLessons: 'Leçons Quotidiennes',
        featuredBooks: 'Livres en Vedette',
        recentlyRead: 'Lus Récemment',
        favorites: 'Favoris',
        categories: 'Catégories',
        allBooks: 'Tous les Livres',
        audioBooks: 'Livres Audio',
        readAloud: 'Lire à Haute Voix',
        autoPlay: 'Lecture Automatique',
        voice: 'Voix',
        language: 'Langue',
        selectLanguage: 'Sélectionner la Langue',
        watchVideo: 'Regarder la Vidéo',
        devotional: 'Dévotion',
        activity: 'Activité',
        quiz: 'Quiz',
        takeQuiz: 'Faire le Quiz',
        episode: 'Épisode',
        account: 'Compte',
        notifications: 'Notifications',
        appearance: 'Apparence',
        privacy: 'Confidentialité',
        help: 'Aide',
        about: 'À propos',
        audioNotifications: 'Audio et Notifications',
        backgroundMusic: 'Musique de Fond',
        soundEffects: 'Effets Sonores',
        appLanguage: "Langue de l'App",
        loading: 'Chargement...',
        error: 'Erreur',
        success: 'Succès',
        noResults: 'Aucun résultat trouvé',
        searchPlaceholder: 'Rechercher...',
        welcome: 'Bienvenue',
        greatJob: 'Excellent travail!',
        keepGoing: 'Continuez!',
        theEnd: 'Fin!',
        whatNext: 'Super lecture! Et maintenant?',
        readAgain: 'Relire',
        addToFavorites: 'Ajouter aux Favoris',
        removeFromFavorites: 'Retirer des Favoris',
        adventureAwaits: "L'Aventure Vous Attend!",
        termsConditions: 'En continuant, vous acceptez nos Conditions Générales',
        appDisplayLanguage: "L'application sera affichée dans la langue sélectionnée",
        changesLanguageInterface: "Change la langue de l'interface de l'application et traduit automatiquement le texte des livres.",
        
        // Onboarding
        welcomeToGodlyKids: 'Bienvenue chez Godly Kids!',
        discoverAmazingStories: 'Découvrez des histoires bibliques incroyables',
        learnAndGrow: 'Apprendre et Grandir',
        buildYourFaith: 'Construisez votre foi avec des activités amusantes',
        readAndListen: 'Lire et Écouter',
        enjoyInteractiveBooks: 'Profitez de livres interactifs avec audio',
        trackProgress: 'Suivre les Progrès',
        seeYourGrowth: 'Voyez votre croissance et vos réalisations',
        getStarted: 'Commencer',
        letsGo: 'Allons-y!',
        yourAvatar: 'Votre Avatar',
        readyForAdventures: 'Prêt pour les Aventures!',
        goPremium: 'Passer Premium',
        editProfile: 'Modifier le Profil',
        visitShop: 'Visiter la Boutique',
        builderShop: 'Boutique du Constructeur',
        customizeYourAvatar: 'Personnalisez votre Avatar',
        heads: 'Têtes',
        bodies: 'Corps',
        hats: 'Chapeaux',
        accessories: 'Accessoires',
        backgrounds: 'Arrière-plans',
        equipped: 'Équipé',
        equip: 'Équiper',
        buy: 'Acheter',
        coins: 'Pièces',
        owned: 'Possédé',
        locked: 'Verrouillé',
        support: 'Support',
        privacyPolicy: 'Politique de Confidentialité',
        termsAndConditions: 'Conditions Générales',
        helpCenter: "Centre d'Aide",
        restorePurchases: 'Restaurer les Achats',
        contactUs: 'Nous Contacter',
        version: 'Version',
        books: 'Livres',
        audio: 'Audio',
        lessons: 'Leçons',
        games: 'Jeux',
        reportCard: 'Bulletin',
        yourProgress: 'Votre Progrès',
        booksRead: 'Livres Lus',
        lessonsCompleted: 'Leçons Terminées',
        daysStreak: 'Jours Consécutifs',
        totalPoints: 'Points Totaux',
        achievements: 'Réalisations',
        keepItUp: 'Continuez!',
        dailyChallenge: 'Défi Quotidien',
        memoryGame: 'Jeu de Mémoire',
        prayerTime: 'Heure de Prière',
        strengthBuilder: 'Constructeur de Force',
        playNow: 'Jouer Maintenant',
        highScore: 'Meilleur Score',
        divinePairs: 'Paires Divines',
        comeBackSoon: 'Revenez Bientôt!',
        memoryChallengeCompleted: 'Vous avez déjà terminé le défi de mémoire d\'aujourd\'hui. Le prochain défi sera disponible dans:',
        resetsEvery12Hours: '(Réinitialisation toutes les 12 heures)',
        memoryChallenge: 'Défi de Mémoire',
        flipCardsToMatch: 'Retournez les cartes pour associer les symboles divins!',
        findThemQuickly: 'Trouvez-les tous rapidement pour 3 étoiles.',
        startGame: 'COMMENCER',
        pairs: 'Paires',
        timesUp: 'Temps Écoulé!',
        keepPracticing: 'Continuez à pratiquer votre mémoire!',
        tryAgain: 'RÉESSAYER',
        sharpMind: 'ESPRIT VIF!',
        foundAllPairs: 'Vous avez trouvé toutes les paires divines!',
        claimCoins: 'RÉCLAMER',
        strengthBuilderGame: 'Constructeur de Force',
        spiritualStrength: 'Force Spirituelle',
        verseChallenge: 'Défi de Versets',
        reciteVerse: 'Récitez le verset correctement!',
        tapWordsInOrder: 'Appuyez sur les mots dans l\'ordre',
        verseCompleted: 'Verset Complété!',
        excellent: 'Excellent!',
        prayerTimeGame: 'Heure de Prière',
        dailyPrayer: 'Prière Quotidienne',
        writeYourPrayer: 'Écrivez votre prière...',
        submitPrayer: 'Soumettre la Prière',
        prayerSubmitted: 'Prière Soumise!',
        thankYouForPraying: 'Merci de prier!',
        overview: 'Aperçu',
        activityHistory: 'Activité',
        thisWeek: 'Cette Semaine',
        thisMonth: 'Ce Mois',
        pagesReadStat: 'Pages Lues',
        songsListened: 'Chansons Écoutées',
        gamesPlayed: 'Jeux Joués',
        coinsEarned: 'Pièces Gagnées',
        timeSpent: 'Temps Passé',
        recentActivity: 'Activité Récente',
        noRecentActivity: 'Aucune activité récente trouvée',
        justNow: 'À l\'instant',
        minsAgo: 'm passées',
        hoursAgo: 'h passées',
        daysAgo: 'j passés',
        playlist: 'Playlist',
        tracks: 'pistes',
        duration: 'Durée',
        playAll: 'Tout Lire',
        shuffle: 'Aléatoire',
        description: 'Description',
        moreInfo: 'Plus d\'Infos',
        ageGroup: "Groupe d'Âge",
        level: 'Niveau',
        premium: 'Premium',
        free: 'Gratuit',
        new: 'Nouveau',
        popular: 'Populaire',
        recommended: 'Recommandé',
        complete: 'Complet',
        incomplete: 'Incomplet',
        start: 'Démarrer',
        resume: 'Reprendre',
        profiles: 'Profils',
        chooseExplorer: 'Choisir Explorateur',
        whosPlayingToday: 'Qui joue aujourd\'hui?',
        addProfile: 'Ajouter Profil',
        parent: 'Parent',
        hiExplorer: 'Salut Explorateur!',
        letsDiveIn: 'Plongeons.',
        thisWeeksProgress: 'Progrès de cette Semaine',
        days: 'Jours',
        dailyTasksIQGames: 'Tâches Quotidiennes et Jeux de QI',
        restPlayDay: 'Jour de Repos et Jeu!',
        noLessonsToday: 'Pas de leçons aujourd\'hui. Profitez de lire des histoires ou de jouer en famille!',
        tapAnotherDay: 'Appuyez sur un autre jour ci-dessus pour voir ces leçons.',
        byAuthor: 'par',
        readNow: 'Lire Maintenant',
        listenNow: 'Écouter Maintenant',
        pages: 'pages',
        minutes: 'minutes',
        allCategories: 'Toutes les Catégories',
        bibleStories: 'Histoires Bibliques',
        faithValues: 'Foi et Valeurs',
        prayerDevotional: 'Prière et Dévotion',
        seeAll: 'Voir Tout',
        viewAll: 'Voir Tout',
        search: 'Rechercher',
        filter: 'Filtrer',
        sort: 'Trier',
    },
    de: {
        home: 'Startseite',
        explore: 'Entdecken',
        read: 'Lesen',
        listen: 'Hören',
        settings: 'Einstellungen',
        profile: 'Profil',
        library: 'Bibliothek',
        play: 'Abspielen',
        pause: 'Pause',
        stop: 'Stoppen',
        continue: 'Weiter',
        next: 'Nächste',
        back: 'Zurück',
        skip: 'Überspringen',
        retry: 'Erneut versuchen',
        save: 'Speichern',
        cancel: 'Abbrechen',
        close: 'Schließen',
        done: 'Fertig',
        signIn: 'Anmelden',
        signOut: 'Abmelden',
        logOut: 'ABMELDEN',
        dailyLessons: 'Tägliche Lektionen',
        featuredBooks: 'Empfohlene Bücher',
        recentlyRead: 'Kürzlich Gelesen',
        favorites: 'Favoriten',
        categories: 'Kategorien',
        allBooks: 'Alle Bücher',
        audioBooks: 'Hörbücher',
        readAloud: 'Vorlesen',
        autoPlay: 'Automatische Wiedergabe',
        voice: 'Stimme',
        language: 'Sprache',
        selectLanguage: 'Sprache Auswählen',
        watchVideo: 'Video Ansehen',
        devotional: 'Andacht',
        activity: 'Aktivität',
        quiz: 'Quiz',
        takeQuiz: 'Quiz Machen',
        episode: 'Episode',
        account: 'Konto',
        notifications: 'Benachrichtigungen',
        appearance: 'Aussehen',
        privacy: 'Datenschutz',
        help: 'Hilfe',
        about: 'Über',
        audioNotifications: 'Audio & Benachrichtigungen',
        backgroundMusic: 'Hintergrundmusik',
        soundEffects: 'Soundeffekte',
        appLanguage: 'App-Sprache',
        loading: 'Laden...',
        error: 'Fehler',
        success: 'Erfolg',
        noResults: 'Keine Ergebnisse gefunden',
        searchPlaceholder: 'Suchen...',
        welcome: 'Willkommen',
        greatJob: 'Tolle Arbeit!',
        keepGoing: 'Weiter so!',
        theEnd: 'Ende!',
        whatNext: 'Toll gelesen! Was kommt als nächstes?',
        readAgain: 'Nochmal Lesen',
        addToFavorites: 'Zu Favoriten Hinzufügen',
        removeFromFavorites: 'Aus Favoriten Entfernen',
        adventureAwaits: 'Abenteuer Wartet!',
        termsConditions: 'Durch Fortfahren stimmst du unseren AGB zu',
        appDisplayLanguage: 'Die App wird in der ausgewählten Sprache angezeigt',
        changesLanguageInterface: 'Ändert die Sprache der App-Oberfläche und übersetzt automatisch den Buchtext.',
        
        // Onboarding
        welcomeToGodlyKids: 'Willkommen bei Godly Kids!',
        discoverAmazingStories: 'Entdecke erstaunliche Bibelgeschichten',
        learnAndGrow: 'Lernen und Wachsen',
        buildYourFaith: 'Baue deinen Glauben mit lustigen Aktivitäten auf',
        readAndListen: 'Lesen und Hören',
        enjoyInteractiveBooks: 'Genieße interaktive Bücher mit Audio',
        trackProgress: 'Fortschritt Verfolgen',
        seeYourGrowth: 'Sieh dein Wachstum und deine Erfolge',
        getStarted: 'Loslegen',
        letsGo: 'Los geht\'s!',
        yourAvatar: 'Dein Avatar',
        readyForAdventures: 'Bereit für Abenteuer!',
        goPremium: 'Premium werden',
        editProfile: 'Profil Bearbeiten',
        visitShop: 'Shop Besuchen',
        builderShop: 'Builder Shop',
        customizeYourAvatar: 'Passe deinen Avatar an',
        heads: 'Köpfe',
        bodies: 'Körper',
        hats: 'Hüte',
        accessories: 'Zubehör',
        backgrounds: 'Hintergründe',
        equipped: 'Ausgerüstet',
        equip: 'Ausrüsten',
        buy: 'Kaufen',
        coins: 'Münzen',
        owned: 'Besitzt',
        locked: 'Gesperrt',
        support: 'Support',
        privacyPolicy: 'Datenschutzrichtlinie',
        termsAndConditions: 'Allgemeine Geschäftsbedingungen',
        helpCenter: 'Hilfezentrum',
        restorePurchases: 'Käufe Wiederherstellen',
        contactUs: 'Kontaktiere Uns',
        version: 'Version',
        books: 'Bücher',
        audio: 'Audio',
        lessons: 'Lektionen',
        games: 'Spiele',
        reportCard: 'Zeugnis',
        yourProgress: 'Dein Fortschritt',
        booksRead: 'Bücher Gelesen',
        lessonsCompleted: 'Lektionen Abgeschlossen',
        daysStreak: 'Tage in Folge',
        totalPoints: 'Gesamtpunkte',
        achievements: 'Erfolge',
        keepItUp: 'Weiter so!',
        dailyChallenge: 'Tägliche Herausforderung',
        memoryGame: 'Gedächtnisspiel',
        prayerTime: 'Gebetszeit',
        strengthBuilder: 'Stärkeaufbau',
        playNow: 'Jetzt Spielen',
        highScore: 'Höchstpunktzahl',
        divinePairs: 'Göttliche Paare',
        comeBackSoon: 'Komm Bald Wieder!',
        memoryChallengeCompleted: 'Du hast die heutige Gedächtnisherausforderung bereits abgeschlossen. Die nächste Herausforderung ist verfügbar in:',
        resetsEvery12Hours: '(Setzt alle 12 Stunden zurück)',
        memoryChallenge: 'Gedächtnisherausforderung',
        flipCardsToMatch: 'Drehe die Karten um, um die göttlichen Symbole zu finden!',
        findThemQuickly: 'Finde sie alle schnell für 3 Sterne.',
        startGame: 'STARTEN',
        pairs: 'Paare',
        timesUp: 'Zeit Abgelaufen!',
        keepPracticing: 'Übe weiter dein Gedächtnis!',
        tryAgain: 'NOCHMAL VERSUCHEN',
        sharpMind: 'SCHARFER VERSTAND!',
        foundAllPairs: 'Du hast alle göttlichen Paare gefunden!',
        claimCoins: 'EINLÖSEN',
        strengthBuilderGame: 'Stärkeaufbau',
        spiritualStrength: 'Spirituelle Stärke',
        verseChallenge: 'Versherausforderung',
        reciteVerse: 'Rezitiere den Vers richtig!',
        tapWordsInOrder: 'Tippe die Wörter in der Reihenfolge',
        verseCompleted: 'Vers Abgeschlossen!',
        excellent: 'Ausgezeichnet!',
        prayerTimeGame: 'Gebetszeit',
        dailyPrayer: 'Tägliches Gebet',
        writeYourPrayer: 'Schreibe dein Gebet...',
        submitPrayer: 'Gebet Senden',
        prayerSubmitted: 'Gebet Gesendet!',
        thankYouForPraying: 'Danke fürs Beten!',
        overview: 'Übersicht',
        activityHistory: 'Aktivität',
        thisWeek: 'Diese Woche',
        thisMonth: 'Diesen Monat',
        pagesReadStat: 'Gelesene Seiten',
        songsListened: 'Gehörte Lieder',
        gamesPlayed: 'Gespielte Spiele',
        coinsEarned: 'Verdiente Münzen',
        timeSpent: 'Verbrachte Zeit',
        recentActivity: 'Letzte Aktivität',
        noRecentActivity: 'Keine aktuelle Aktivität gefunden',
        justNow: 'Gerade eben',
        minsAgo: 'm her',
        hoursAgo: 'h her',
        daysAgo: 'T her',
        playlist: 'Playlist',
        tracks: 'Titel',
        duration: 'Dauer',
        playAll: 'Alles Abspielen',
        shuffle: 'Zufällig',
        description: 'Beschreibung',
        moreInfo: 'Mehr Info',
        ageGroup: 'Altersgruppe',
        level: 'Level',
        premium: 'Premium',
        free: 'Kostenlos',
        new: 'Neu',
        popular: 'Beliebt',
        recommended: 'Empfohlen',
        complete: 'Vollständig',
        incomplete: 'Unvollständig',
        start: 'Starten',
        resume: 'Fortsetzen',
        profiles: 'Profile',
        chooseExplorer: 'Wähle Entdecker',
        whosPlayingToday: 'Wer spielt heute?',
        addProfile: 'Profil Hinzufügen',
        parent: 'Elternteil',
        hiExplorer: 'Hallo Entdecker!',
        letsDiveIn: 'Lass uns eintauchen.',
        thisWeeksProgress: 'Fortschritt dieser Woche',
        days: 'Tage',
        dailyTasksIQGames: 'Tägliche Aufgaben & IQ-Spiele',
        restPlayDay: 'Ruhe- und Spieltag!',
        noLessonsToday: 'Keine Lektionen heute. Genieße Geschichten oder spiele mit der Familie!',
        tapAnotherDay: 'Tippe oben auf einen anderen Tag, um diese Lektionen anzuzeigen.',
        byAuthor: 'von',
        readNow: 'Jetzt Lesen',
        listenNow: 'Jetzt Hören',
        pages: 'Seiten',
        minutes: 'Minuten',
        allCategories: 'Alle Kategorien',
        bibleStories: 'Bibelgeschichten',
        faithValues: 'Glaube & Werte',
        prayerDevotional: 'Gebet & Andacht',
        seeAll: 'Alle Anzeigen',
        viewAll: 'Alle Anzeigen',
        search: 'Suchen',
        filter: 'Filtern',
        sort: 'Sortieren',
    },
    tl: {
        home: 'Home',
        explore: 'Mag-explore',
        read: 'Magbasa',
        listen: 'Makinig',
        settings: 'Mga Setting',
        profile: 'Profile',
        library: 'Aklatan',
        play: 'I-play',
        pause: 'I-pause',
        stop: 'Itigil',
        continue: 'Magpatuloy',
        next: 'Susunod',
        back: 'Bumalik',
        skip: 'Laktawan',
        retry: 'Subukan Muli',
        save: 'I-save',
        cancel: 'Kanselahin',
        close: 'Isara',
        done: 'Tapos',
        signIn: 'Mag-sign In',
        signOut: 'Mag-sign Out',
        logOut: 'MAG-LOG OUT',
        dailyLessons: 'Mga Araw-araw na Aralin',
        featuredBooks: 'Mga Tampok na Libro',
        recentlyRead: 'Kamakailang Binasa',
        favorites: 'Mga Paborito',
        categories: 'Mga Kategorya',
        allBooks: 'Lahat ng Libro',
        audioBooks: 'Mga Audio Book',
        readAloud: 'Basahin Nang Malakas',
        autoPlay: 'Auto Play',
        voice: 'Boses',
        language: 'Wika',
        selectLanguage: 'Pumili ng Wika',
        watchVideo: 'Manood ng Video',
        devotional: 'Debosyonal',
        activity: 'Aktibidad',
        quiz: 'Pagsusulit',
        takeQuiz: 'Kumuha ng Pagsusulit',
        episode: 'Episode',
        account: 'Account',
        notifications: 'Mga Notification',
        appearance: 'Hitsura',
        privacy: 'Privacy',
        help: 'Tulong',
        about: 'Tungkol Sa',
        audioNotifications: 'Audio at Mga Notification',
        backgroundMusic: 'Background Music',
        soundEffects: 'Mga Sound Effect',
        appLanguage: 'Wika ng App',
        loading: 'Naglo-load...',
        error: 'Error',
        success: 'Tagumpay',
        noResults: 'Walang nakitang resulta',
        searchPlaceholder: 'Maghanap...',
        welcome: 'Maligayang Pagdating',
        greatJob: 'Magaling!',
        keepGoing: 'Ituloy mo!',
        theEnd: 'Wakas!',
        whatNext: 'Mahusay na pagbabasa! Ano ang susunod?',
        readAgain: 'Basahin Muli',
        addToFavorites: 'Idagdag sa Paborito',
        removeFromFavorites: 'Alisin sa Paborito',
        adventureAwaits: 'Naghihintay ang Pakikipagsapalaran!',
        termsConditions: 'Sa pagpapatuloy, sumasang-ayon ka sa aming Mga Tuntunin at Kundisyon',
        appDisplayLanguage: 'Ipapakita ang app sa napiling wika',
        changesLanguageInterface: 'Binabago ang wika ng interface ng app at awtomatikong isinasalin ang teksto ng libro.',
        
        // Onboarding
        welcomeToGodlyKids: 'Maligayang Pagdating sa Godly Kids!',
        discoverAmazingStories: 'Tuklasin ang mga kamangha-manghang kuwento ng Bibliya',
        learnAndGrow: 'Matuto at Lumago',
        buildYourFaith: 'Itayo ang iyong pananampalataya sa mga masasayang aktibidad',
        readAndListen: 'Magbasa at Makinig',
        enjoyInteractiveBooks: 'Mag-enjoy sa mga interactive na libro na may audio',
        trackProgress: 'Subaybayan ang Progreso',
        seeYourGrowth: 'Tingnan ang iyong paglago at mga tagumpay',
        getStarted: 'Magsimula',
        letsGo: 'Tara na!',
        yourAvatar: 'Ang Iyong Avatar',
        readyForAdventures: 'Handa na para sa mga Pakikipagsapalaran!',
        goPremium: 'Mag-Premium',
        editProfile: 'I-edit ang Profile',
        visitShop: 'Bisitahin ang Tindahan',
        builderShop: 'Builder Shop',
        customizeYourAvatar: 'I-customize ang iyong Avatar',
        heads: 'Mga Ulo',
        bodies: 'Mga Katawan',
        hats: 'Mga Sumbrero',
        accessories: 'Mga Aksesori',
        backgrounds: 'Mga Background',
        equipped: 'Naka-equip',
        equip: 'I-equip',
        buy: 'Bumili',
        coins: 'Mga Barya',
        owned: 'Pag-aari',
        locked: 'Naka-lock',
        support: 'Suporta',
        privacyPolicy: 'Patakaran sa Privacy',
        termsAndConditions: 'Mga Tuntunin at Kundisyon',
        helpCenter: 'Help Center',
        restorePurchases: 'Ibalik ang mga Pagbili',
        contactUs: 'Makipag-ugnayan',
        version: 'Bersyon',
        books: 'Mga Libro',
        audio: 'Audio',
        lessons: 'Mga Aralin',
        games: 'Mga Laro',
        reportCard: 'Report Card',
        yourProgress: 'Ang Iyong Progreso',
        booksRead: 'Mga Librong Nabasa',
        lessonsCompleted: 'Mga Aralin na Nakumpleto',
        daysStreak: 'Mga Sunod-sunod na Araw',
        totalPoints: 'Kabuuang Puntos',
        achievements: 'Mga Tagumpay',
        keepItUp: 'Ipagpatuloy!',
        dailyChallenge: 'Pang-araw-araw na Hamon',
        memoryGame: 'Memory Game',
        prayerTime: 'Oras ng Panalangin',
        strengthBuilder: 'Tagapagtayo ng Lakas',
        playNow: 'Maglaro Ngayon',
        highScore: 'Pinakamataas na Iskor',
        playlist: 'Playlist',
        tracks: 'mga track',
        duration: 'Tagal',
        playAll: 'I-play Lahat',
        shuffle: 'I-shuffle',
        description: 'Paglalarawan',
        moreInfo: 'Higit pang Impormasyon',
        ageGroup: 'Grupo ng Edad',
        level: 'Antas',
        premium: 'Premium',
        free: 'Libre',
        new: 'Bago',
        popular: 'Sikat',
        recommended: 'Inirerekomenda',
        complete: 'Kumpleto',
        incomplete: 'Hindi Kumpleto',
        start: 'Simulan',
        resume: 'Ipagpatuloy',
        profiles: 'Mga Profile',
        chooseExplorer: 'Pumili ng Explorer',
        whosPlayingToday: 'Sino ang maglalaro ngayon?',
        addProfile: 'Magdagdag ng Profile',
        parent: 'Magulang',
        hiExplorer: 'Kamusta Explorer!',
        letsDiveIn: 'Tara na, sumabak tayo.',
        thisWeeksProgress: 'Progreso Ngayong Linggo',
        days: 'Mga Araw',
        dailyTasksIQGames: 'Pang-araw-araw na Gawain at IQ Games',
        restPlayDay: 'Araw ng Pahinga at Paglalaro!',
        noLessonsToday: 'Walang aralin ngayon. Mag-enjoy sa pagbabasa ng mga kuwento o paglalaro kasama ang pamilya!',
        tapAnotherDay: 'Pindutin ang ibang araw sa itaas para makita ang mga aralin.',
        byAuthor: 'ni',
        readNow: 'Basahin Ngayon',
        listenNow: 'Pakinggan Ngayon',
        pages: 'mga pahina',
        minutes: 'minuto',
        allCategories: 'Lahat ng Kategorya',
        bibleStories: 'Mga Kuwento ng Bibliya',
        faithValues: 'Pananampalataya at mga Halaga',
        prayerDevotional: 'Panalangin at Debosyon',
        seeAll: 'Tingnan Lahat',
        viewAll: 'Tingnan Lahat',
        search: 'Maghanap',
        filter: 'I-filter',
        sort: 'Ayusin',
    },
};

// For languages not pre-translated, we'll use the backend API
const getTranslationForLanguage = (lang: string, key: string): string | null => {
    return UI_TRANSLATIONS[lang]?.[key] || null;
};

// Cache for dynamically translated content
const translationCache = new Map<string, string>();

interface LanguageContextType {
    currentLanguage: string;
    setLanguage: (lang: string) => void;
    t: (key: string) => string; // Translate UI text
    translateText: (text: string) => Promise<string>; // Translate dynamic content
    translateTexts: (texts: string[]) => Promise<string[]>; // Batch translate
    isTranslating: boolean;
    supportedLanguages: typeof SUPPORTED_LANGUAGES;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const LANGUAGE_STORAGE_KEY = 'godlykids_app_language';

interface LanguageProviderProps {
    children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
    const [currentLanguage, setCurrentLanguage] = useState<string>(() => {
        return localStorage.getItem(LANGUAGE_STORAGE_KEY) || 'en';
    });
    const [isTranslating, setIsTranslating] = useState(false);
    const [apiTranslations, setApiTranslations] = useState<Record<string, Record<string, string>>>({});

    // Save language preference and sync with book reader
    const setLanguage = useCallback((lang: string) => {
        setCurrentLanguage(lang);
        localStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
        // Also sync with book reader language preference
        localStorage.setItem('godlykids_reader_language', lang);
    }, []);

    // Translate static UI text - instant for pre-translated languages
    const t = useCallback((key: string): string => {
        // First check pre-translated strings
        const preTranslated = getTranslationForLanguage(currentLanguage, key);
        if (preTranslated) {
            return preTranslated;
        }

        // Check API-fetched translations
        if (apiTranslations[currentLanguage]?.[key]) {
            return apiTranslations[currentLanguage][key];
        }

        // Return English as fallback
        return UI_TRANSLATIONS.en[key] || key;
    }, [currentLanguage, apiTranslations]);

    // Fetch translations from API for languages not pre-translated
    useEffect(() => {
        const fetchMissingTranslations = async () => {
            // Skip if we have pre-translated strings for this language
            if (UI_TRANSLATIONS[currentLanguage]) return;
            if (currentLanguage === 'en') return;
            if (apiTranslations[currentLanguage]) return; // Already fetched

            setIsTranslating(true);
            try {
                const englishStrings = UI_TRANSLATIONS.en;
                const keys = Object.keys(englishStrings);
                const texts = Object.values(englishStrings);

                const response = await fetch(`${getApiBaseUrl()}translate/ui`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ texts, lang: currentLanguage }),
                });

                if (response.ok) {
                    const data = await response.json();
                    const translated: Record<string, string> = {};
                    keys.forEach((key, index) => {
                        translated[key] = data.translations[index] || englishStrings[key];
                    });

                    setApiTranslations(prev => ({
                        ...prev,
                        [currentLanguage]: translated,
                    }));
                }
            } catch (error) {
                console.error('Failed to translate UI strings:', error);
            } finally {
                setIsTranslating(false);
            }
        };

        fetchMissingTranslations();
    }, [currentLanguage, apiTranslations]);

    // Translate dynamic content (book titles, descriptions, etc.)
    const translateText = useCallback(async (text: string): Promise<string> => {
        if (!text || currentLanguage === 'en') return text;

        const cacheKey = `${currentLanguage}_${text}`;
        if (translationCache.has(cacheKey)) {
            return translationCache.get(cacheKey)!;
        }

        try {
            const response = await fetch(
                `${getApiBaseUrl()}translate/text?lang=${currentLanguage}`,
                {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ text }),
                }
            );

            if (response.ok) {
                const data = await response.json();
                translationCache.set(cacheKey, data.translatedText);
                return data.translatedText;
            }
        } catch (error) {
            console.error('Translation error:', error);
        }

        return text;
    }, [currentLanguage]);

    // Batch translate multiple texts
    const translateTexts = useCallback(async (texts: string[]): Promise<string[]> => {
        if (currentLanguage === 'en') return texts;

        const results: string[] = [];
        const uncachedTexts: string[] = [];
        const uncachedIndices: number[] = [];

        texts.forEach((text, index) => {
            const cacheKey = `${currentLanguage}_${text}`;
            if (translationCache.has(cacheKey)) {
                results[index] = translationCache.get(cacheKey)!;
            } else {
                uncachedTexts.push(text);
                uncachedIndices.push(index);
            }
        });

        if (uncachedTexts.length === 0) {
            return results;
        }

        try {
            const response = await fetch(
                `${getApiBaseUrl()}translate/texts?lang=${currentLanguage}`,
                {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ texts: uncachedTexts }),
                }
            );

            if (response.ok) {
                const data = await response.json();
                data.translations.forEach((translated: string, i: number) => {
                    const originalIndex = uncachedIndices[i];
                    const originalText = uncachedTexts[i];
                    const cacheKey = `${currentLanguage}_${originalText}`;
                    translationCache.set(cacheKey, translated);
                    results[originalIndex] = translated;
                });
            }
        } catch (error) {
            console.error('Batch translation error:', error);
            uncachedIndices.forEach((index, i) => {
                if (!results[index]) results[index] = uncachedTexts[i];
            });
        }

        return results;
    }, [currentLanguage]);

    const value: LanguageContextType = {
        currentLanguage,
        setLanguage,
        t,
        translateText,
        translateTexts,
        isTranslating,
        supportedLanguages: SUPPORTED_LANGUAGES,
    };

    return (
        <LanguageContext.Provider value={value}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = (): LanguageContextType => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};

export default LanguageContext;
